FROM python:3.6.5-slim-stretch

WORKDIR /opt/RyuGoo-Saba/SabaMaster
COPY ./requirements.txt /opt/RyuGoo-Saba/SabaMaster/
RUN pip3 install --no-cache-dir -r requirements.txt

# COPY ./pySabaMaster /opt/RyuGoo-Saba/SabaMaster/pySabaMaster
CMD ["tail", "-f", "/dev/null"]
