version: '3'
services:
  api_server:
    image: saba_master/api_server
    build:
      context: .
      dockerfile: Dockerfile-api_server
    restart: always
    tty: true
    ports:
      - "8080:8080"
    environment:
      PYTHONPATH: "/opt/RyuGoo-Saba/SabaMaster"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /opt/RyuGoo-Saba/SabaMaster/ssl_certification:/opt/RyuGoo-Saba/SabaMaster/ssl_certification
      - /opt/RyuGoo-Saba/SabaMaster/pySabaMaster:/opt/RyuGoo-Saba/SabaMaster/pySabaMaster
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - azure_cli
      - postgres
    command: ["python3", "/opt/RyuGoo-Saba/SabaMaster/pySabaMaster/app.py"]
  redis:
    image: redis:4.0.9-alpine
    restart: always
    tty: true
    expose:
      - "6379"
    volumes:
      - redis_data:/data
  azure_cli:
    image: microsoft/azure-cli:latest
    restart: always
    tty: true
  postgres:
    image: postgres:9.6.3-alpine
    restart: always
    tty: true
    expose:
      - "5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=passwd"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  redis_data:
