FROM python:3.6.5-slim-stretch

RUN apt-get update \
 && apt-get install -y \
    gnupg2 \
    curl \
    lsb-release \
    jq

RUN echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 \
 && apt-get update \
 && apt-get install -y ansible

RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
 && curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
 && apt-get install -y apt-transport-https \
 && apt-get update \
 && apt-get install -y azure-cli

WORKDIR /opt/RyuGoo-Saba/SabaCLI

COPY requirements.txt /opt/RyuGoo-Saba/SabaCLI/
RUN pip3 install --no-cache-dir -r requirements.txt

# COPY pySabaCLI /opt/RyuGoo-Saba/SabaCLI/pySabaCLI
# COPY ansible-master /opt/RyuGoo-Saba/SabaCLI/ansible-master
RUN echo 'alias saba="python3 /opt/RyuGoo-Saba/SabaCLI/pySabaCLI"' >> ~/.bashrc

CMD ["tail", "-f", "/dev/null"]
